server/server/Models/user.js
server/server/__tests__/models-tests/user.test.js
server/server/__tests__/user.test.js

created user schema and model, with unit tests

---

server/server/Models/cart.js
server/server/__tests__/models-tests/cart.test.js

- each cart will have unique userId so user will have single cart.
- items array in cart will have distinct documents based on itemId, adding more of the same item should only add to quantity not creating new item document in items array.
- the cart will self delete in approx. 45 minutes.
closes #4

created Cart mongoose schema and model, with unit tests

---

server/server/Models/order.js
server/server/__tests__/models-tests/order.test.js

created Order mongoose schema and model, with unit tests

---

server/server/Models/restaurant.js

The model is designed to capture essential information about a restaurant and is equipped with necessary validations.
Further enhancements, such as specifying the data type for restaurantPicture  and setting default values, can be considered in future updates.
closes #2

create restaurant mongoose schema and model

---

server/server/Models/order.js
server/server/Models/restaurant.js
server/server/Models/user.js
server/server/__tests__/models-tests/user.test.js

fix error message in models for location, fix phoneNumber in user

---

server/server/Routes/v1.js
server/server/index.js

setup backend structure for API url versioning

---

server/server/Models/review.js
server/server/__tests__/models-tests/review.test.js

created review model, with test

---

server/server/Models/order.js
server/server/Models/restaurant.js

fixes for order and restaurant schemas

---

server/server/Models/item.js

create item mongoose schema and model

---

server/package-lock.json
server/package.json
server/server/Controllers/restaurant.js
server/server/Controllers/restaurant.utils.js
server/server/Routes/restaurant.js
server/server/Routes/v1.js
server/yarn.lock

Public API GET restaurant list route and controller

---

server/server/Controllers/item.js

- extracts filter parameters from the query string (e.g., category, priceRange, availableQuantity)
- added pagination to show a limit of 20 items per page
closes #26

create item GET request controller with filter functionality

---

package-lock.json
server/package-lock.json
server/package.json
server/server/Controllers/signingController.js
server/server/Middlewares/passportAuthMiddleware.js
server/server/Routes/signRoutes.js
server/server/configs/passport.js
server/server/index.js
server/server/utils/createTokens.js
server/yarn.lock

JWT authentication implementation with access and refresh tokens

---

server/server/Controllers/adminCrud.js
server/server/Routes/admin.js
server/server/index.js

add admin CRUD on item model

---

server/server/Middlewares/authorizeAdmin.js
server/server/Middlewares/passportAuthMiddleware.js
server/server/index.js

Created admin authorization middleware

---

server/server/Controllers/adminController.js
server/server/Routes/adminRoutes.js

created admin controller to retrieve current-delivering-orders

---

server/server/Controllers/adminController.js
server/server/Routes/adminRoutes.js

created admin controller to update the order status

---

server/.env
server/server/db/connection.js

Setup mongoDB Atlas connection

---

server/server/Controllers/customerController.js
server/server/Routes/customerRoutes.js

the customer should be able to:
1. the user will try to add or change item quantity to his cart
2. first we check itemID if exists in database, then extract price, quantity, and restaurantID from item
3. we need to check if item has enough quantity to add to user cart
4. we need to check if the user already has a cart document or not
5. if user doesn't have cart document, we create new cart with the itemID and quantity
6. if user has cart, we need to check if itemID is from same restaurantID in cart, and if already in items array of cart
7. if itemID doesn't exist, we just push the new itemID with quantity / if itemID exists, we arithmetically add to quantity field of itemID
closes #44

user cart CRUD - routes and controllers

---

client/src/app/SignIn/page.js

**I'm looking forward to hearing your feedback**
closes #83

create sign in page

---

client/src/app/SignUp/page.js

should I add phone no. input field?
closes #81

create sign up page

---

client/src/app/components/Restaurant/ReviewCard.jsx

https://github.com/202309-EKTA-JO-FSW/capstone-room-5/assets/80969606/d73f36a4-1562-4012-b26e-5372cc2e6cc8
Closes #79

Review Card

---

client/src/app/SignIn/page.js
client/src/app/SignUp/page.js

editing and enhancing responsivity

---

client/src/app/components/Navbar.jsx
client/src/app/layout.js

created Navbar - still checking mobile version of navbar 
closes #64

Created Navbar

---

client/package-lock.json
client/package.json
client/src/app/SignIn/GoogleSignIn.jsx
client/src/app/SignIn/SignInForm.jsx
client/src/app/SignIn/page.js
client/src/app/SignIn/signin.module.css
client/src/app/components/LandingPage/LandingPageNavbar.jsx
client/src/app/components/Navbar.jsx
client/src/app/layout.js
client/src/app/utils/contextProvider.jsx
server/server/Controllers/signingController.js

Configure Sign in integration with backend

---

client/src/app/singleRestaurantPage/ShoppingCart.jsx

create Shopping Cart Component

---

client/src/app/components/Navbar.jsx
client/src/app/components/Navbar.module.css

 Change navbar overflow css rules for mobiles

---

client/src/app/SignUp/SignUpForm.jsx
client/src/app/SignUp/page.js
client/src/app/SignUp/signup.module.css

https://github.com/202309-EKTA-JO-FSW/capstone-room-5/assets/80969606/f7444d31-6ead-4b20-94af-4c3b03eb1318
Closes #109

Sign Up page integration with Backend

---

client/src/app/SignIn/SignInForm.jsx
client/src/app/SignIn/page.js

set token cookies; edit URL; set user cookie expiration

Sign In integration fixes

---

client/src/app/checkout/PaymentForm.jsx
client/src/app/checkout/PaymentMethod.jsx
client/src/app/checkout/ShoppingCart.jsx
client/src/app/checkout/page.js

created checkout page with payment methods

---

client/src/app/components/Restaurant/RestaurantCard.jsx
client/src/app/restaurants/RestaurantsList.jsx
client/src/app/restaurants/SearchAndList.jsx
client/src/app/restaurants/SearchRestaurants.jsx
client/src/app/restaurants/page.js

Restaurants Page integration

---

client/src/app/components/LandingPage/Search.jsx

Home page search integration

---

client/src/app/components/Restaurant/ItemCard.jsx
client/src/app/restaurant/[id]/MainPage.jsx
client/src/app/restaurant/[id]/ReviewsOrItems.jsx
client/src/app/restaurant/[id]/ShoppingCart.jsx
client/src/app/restaurant/[id]/ShoppingCartRow.jsx
client/src/app/restaurant/[id]/page.js
server/server/Controllers/customerController.js

Cart integration

---

client/src/app/SignIn/page.js
client/src/app/SignUp/page.js
client/src/app/admin/dashboard/page.js
client/src/app/components/GoogleSignIn.jsx
client/src/app/components/Test.jsx
client/src/app/restaurant/[id]/page.js
client/src/app/restaurants/page.js
client/src/app/utils/refreshAccessToken.jsx
server/server/configs/passport.js

Migrating to deployed server

---

client/src/app/SignUp/SignUpForm.jsx
client/src/app/checkout/PaymentForm.jsx
client/src/app/checkout/PaymentMethod.jsx
client/src/app/checkout/ShoppingCart.jsx
client/src/app/checkout/ShoppingCartRow.jsx
client/src/app/checkout/form.module.css
client/src/app/checkout/page.js
client/src/app/components/LandingPage/Search.jsx
client/src/app/restaurant/[id]/MainPage.jsx
client/src/app/restaurant/[id]/ReviewsOrItems.jsx
client/src/app/restaurant/[id]/ShoppingCart.jsx
server/server/Controllers/customerController.js

Checkout page integration

---

client/package.json

Configure build command
